### ISSUE TITLE
Reap changed operation defined objects

### ISSUE THREAD

**Issue by jasonrichardsmith** [slipway-gitops/slipway#6]
**Describe the bug**
The hash controller does not reap old objects if the operation changes and they fall under a different name/namespace for their GVK.

**To Reproduce**
create a repo
```yaml
apiVersion: git.gitops.slipway.org/v1
kind: GitRepo
metadata:
  name: gitrepo-sample
spec:
  uri: "git@github.com:slipway-gitops/slipway-examples.git"
  security: "secret ref?"
  operations:
    - operation: test
      path: "git@github.com:slipway-gitops/slipway-examples.git//kustomize/base"
      weight: 3
      optype: branch
      reference: m[a-z]+r
      transformers:
        - type: annotations
          value: branch
          key: branch-name
        - type: namespace
          value: branch
```

and change the "namespace" to anything else.  The old resources will remain after the update.
```yaml
apiVersion: git.gitops.slipway.org/v1
kind: GitRepo
metadata:
  name: gitrepo-sample
spec:
  uri: "git@github.com:slipway-gitops/slipway-examples.git"
  security: "secret ref?"
  operations:
    - operation: test
      path: "git@github.com:slipway-gitops/slipway-examples.git//kustomize/base"
      weight: 3
      optype: branch
      reference: m[a-z]+r
      transformers:
        - type: annotations
          value: branch
          key: branch-name
        - type: namespace
          value: hash
```

**Expected behavior**
only run objects defined in the operation.  remove all previous ones.
